import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import { ApolloProvider } from '@apollo/client';
import client from '@/lib/apolloClient';
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const montserrat = Montserrat({
    variable: "--font-montserrat",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "RescueLanka",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <head>
            <link rel="icon" href="/favicon.png" type="image/x-icon" />
        </head>
        <body
            className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} antialiased`}
        >
        <ApolloProvider client={client}>
            {children}
        </ApolloProvider>
        </body>
        </html>
    );
}
